In [1]:
# Librerías principales
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
from google.colab import files
uploaded = files.upload()

Saving dataset.xlsx to dataset.xlsx

In [3]:
df = pd.read_excel("dataset.xlsx")

df.head()

,Marca temporal,EDAD,GENERO,ESTRATO NSE,CIUDAD DE ORIGEN,Con quien vive actualmente,Numero de personas en el hogar,Quien realiza las compras en el Hogar,Tu misión de compra es abastecer tu hogar. Con que frecuencia lo haces.,Lugar principal de compra,Presupuesto Mensual aproximado,Alimentos Básicos,Proteinas,Bebidas,Snacks y otros,Delikatessen,Aseo para el Hogar,Aseo Personal,ultima
0,2026-04-01 16:40:21.529,22,Masculino,E3,mani casanare,Familia,3-4,Compartido,Semanal,Tienda de Barrio,300000,Arroz,Carne de Res,Chocolate,Panela,Quesos,Suavizantes,Shampoo,"leche,aceite,arroz,aguacate ,suavitel, deterge..."
1,2026-04-01 16:43:13.904,47,Femenino,E3,Bogotá,Familia,2,Yo,Mensual,"Hard Discount (D1, ARA, etc )",300000,"Arroz, Pastas, Lentejas, Frijoles, Garbanzos","Pollo, Carne de Res, Huevos, Atun, Pescados","Leche, Café, Chocolate","Galletas, Panela, Dulces","Quesos, Jamon, Salchichas, Otros Embutidos, Sa...","Detergente, Papel Higienico, Suavizantes, Lava...","Shampoo, Crema dental, Jabon tocador, Protecci...",Ghjjjjjbv
2,2026-04-01 16:44:10.287,24,Masculino,E4,Santa Marta,Padres,2,Compartido,Semanal,"Supermercado (Exito, Jumbo, Etc)",2500000,"Arroz, Lentejas, Harinas","Pollo, Carne de Cerdo, Huevos, Atun, Pescados","Leche, Café, Gaseosa",ninguno,Salchichas,"Detergente, Papel Higienico, Blanqueadores, Su...","Shampoo, Acondicionador, Crema dental, Jabon t...","aceite,arroz,frijoles,lentejas,leche,salchicha..."
3,2026-04-01 16:52:20.537,20,Femenino,E4,Bogotá,Familia,2,Yo,Semanal,Tienda de Barrio,300000,"Arroz, Frijoles, Harinas","Pollo, Carne de Res, Huevos, Pescados","Leche, Jugos, Agua",chocolate,"Quesos, Jamon, Salchichas, Salsas","Detergente, Papel Higienico, Suavizantes, Lava...","Shampoo, Acondicionador, Crema dental, Hilo De...",Pollo cebolla tomate papas agua leche
4,2026-04-01 19:31:11.449,20,Masculino,E2,Bogotá D.C.,Padres,3,Otra persona,Semanal,"Hard Discount (D1, ARA, etc )",1700000,"Arroz, Pastas, Lentejas, Frijoles, Harinas, Ga...","Pollo, Carne de Res, Huevos, Atun, Pescados","Leche, Café, Jugos, Agua, Te, Chocolate","Galletas, chocolate, Dulces, Cereales, Ponque","Quesos, Jamon, Salchichas, Salsas","Detergente, Papel Higienico, Blanqueadores, Su...","Shampoo, Acondicionador, Crema dental, Jabon t...","Arroz, Aceite, Huevos, Grano seco, Leche, Ques..."

In [4]:
df.columns = df.columns.str.strip().str.lower()
# df.columns = df.columns

print(df.columns)

df.rename(columns={
    'Marca temporal': 'fecha',
    'EDAD': 'edad',
    'GENERO': 'genero',
    'estrato nse': 'estrato_nse',
    'ciudad de origen': 'cuidad_origen',
    'con quien vive actualmente': 'quien_vive',
    'numero de personas en el hogar': 'num_personas',
    'quien realiza las compras en el hogar': 'quien_compra',
    'tu misión de compra es abastecer tu hogar. con que frecuencia lo haces.': 'mision_compra',
    'lugar principal de compra': 'canal_compra',
    'presupuesto mensual aproximado': 'gasto',
    'alimentos básicos': 'alimentos_basicos',
    'proteinas': 'proteinas',
    'bebidas': 'bebidas',
    'snacks y otros': 'snacks',
    'delikatessen': 'delikatessen',
    'aseo para el hogar': 'aseo_hogar',
    'aseo personal': 'aseo_personal',
    'ultima': 'otros',
}, inplace=True)

df.head()

Index(['marca temporal', 'edad', 'genero', 'estrato nse', 'ciudad de origen',
       'con quien vive actualmente', 'numero de personas en el hogar',
       'quien realiza las compras en el hogar',
       'tu misión de compra es abastecer tu hogar. con que frecuencia lo haces.',
       'lugar principal de compra', 'presupuesto mensual aproximado',
       'alimentos básicos', 'proteinas', 'bebidas', 'snacks y otros',
       'delikatessen', 'aseo para el hogar', 'aseo personal', 'ultima'],
      dtype='object')

,marca temporal,edad,genero,estrato,cuidad_origen,quien_vive,num_personas,quien_compra,mision_compra,lugar_compra,presupuesto,alimentos_basicos,proteinas,bebidas,snacks,delikatessen,aseo_hogar,aseo_personal,otros
0,2026-04-01 16:40:21.529,22,Masculino,E3,mani casanare,Familia,3-4,Compartido,Semanal,Tienda de Barrio,300000,Arroz,Carne de Res,Chocolate,Panela,Quesos,Suavizantes,Shampoo,"leche,aceite,arroz,aguacate ,suavitel, deterge..."
1,2026-04-01 16:43:13.904,47,Femenino,E3,Bogotá,Familia,2,Yo,Mensual,"Hard Discount (D1, ARA, etc )",300000,"Arroz, Pastas, Lentejas, Frijoles, Garbanzos","Pollo, Carne de Res, Huevos, Atun, Pescados","Leche, Café, Chocolate","Galletas, Panela, Dulces","Quesos, Jamon, Salchichas, Otros Embutidos, Sa...","Detergente, Papel Higienico, Suavizantes, Lava...","Shampoo, Crema dental, Jabon tocador, Protecci...",Ghjjjjjbv
2,2026-04-01 16:44:10.287,24,Masculino,E4,Santa Marta,Padres,2,Compartido,Semanal,"Supermercado (Exito, Jumbo, Etc)",2500000,"Arroz, Lentejas, Harinas","Pollo, Carne de Cerdo, Huevos, Atun, Pescados","Leche, Café, Gaseosa",ninguno,Salchichas,"Detergente, Papel Higienico, Blanqueadores, Su...","Shampoo, Acondicionador, Crema dental, Jabon t...","aceite,arroz,frijoles,lentejas,leche,salchicha..."
3,2026-04-01 16:52:20.537,20,Femenino,E4,Bogotá,Familia,2,Yo,Semanal,Tienda de Barrio,300000,"Arroz, Frijoles, Harinas","Pollo, Carne de Res, Huevos, Pescados","Leche, Jugos, Agua",chocolate,"Quesos, Jamon, Salchichas, Salsas","Detergente, Papel Higienico, Suavizantes, Lava...","Shampoo, Acondicionador, Crema dental, Hilo De...",Pollo cebolla tomate papas agua leche
4,2026-04-01 19:31:11.449,20,Masculino,E2,Bogotá D.C.,Padres,3,Otra persona,Semanal,"Hard Discount (D1, ARA, etc )",1700000,"Arroz, Pastas, Lentejas, Frijoles, Harinas, Ga...","Pollo, Carne de Res, Huevos, Atun, Pescados","Leche, Café, Jugos, Agua, Te, Chocolate","Galletas, chocolate, Dulces, Cereales, Ponque","Quesos, Jamon, Salchichas, Salsas","Detergente, Papel Higienico, Blanqueadores, Su...","Shampoo, Acondicionador, Crema dental, Jabon t...","Arroz, Aceite, Huevos, Grano seco, Leche, Ques..."

In [5]:
rows_to_cols = [
  "alimentos_basicos",
  "proteinas",
  "bebidas",
  "snacks",
  "delikatessen",
  "aseo_hogar",
  "aseo_personal",
  "otros",
]

First, let's define the `replace_map` for value normalization and `columns_to_exclude` for unwanted columns. You can customize these objects below.

In [6]:
import unicodedata
import re

# Define your custom replacement map here
# Keys are values found in data, values are the normalized form
replace_map = {
    "blanqueadores": "blanqueador",
    "leche": "leche",

    "frijoles": "2 libras de frijol",
    "lentejas": "2 libras de lentejas",
    "bananos": "abanos",
    "arroz": "arros",

}

# Define a list of column names (normalized item names) to exclude from the final DataFrame
columns_to_exclude = [
    "ghjjjjjbv"
]

print("Custom replace_map and columns_to_exclude defined.")

Custom replace_map and columns_to_exclude defined.

In [7]:
from sklearn.preprocessing import MultiLabelBinarizer

# Function to clean and split the text data in the columns
def clean_and_split(text):
    if pd.isna(text):
        return []
    # Ensure text is a string before splitting
    if not isinstance(text, str):
        return []

    # 1. Normalize accents and special characters
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')

    # 2. Replace common separators with a unique marker to ensure correct splitting
    # Replace newline characters with a marker
    text = text.replace('\n', '####')
    # Replace bullet points like "- " or "-" followed by content with a marker
    text = re.sub(r'-\s*', '####', text) # Replace '- ' or '-' with '####'

    # 3. Split by the unique marker and filter out empty strings
    items = [item.strip().lower() for item in text.split('####') if item.strip()]

    # 4. Apply the custom replace_map for further normalization
    processed_items = []
    for item in items:
        if item: # Ensure item is not empty after stripping
            processed_item = replace_map.get(item, item) # Use .get() to apply replacement if key exists, otherwise keep original
            processed_items.append(processed_item)

    # Return unique items to avoid duplicates after replacements
    return sorted(list(set(processed_items)))

# Apply the cleaning and splitting to the relevant columns
processed_data = df[rows_to_cols].applymap(clean_and_split)

# Combine all lists of items for each row
# This creates a list of lists, where each inner list contains all items for a given row
combined_items = processed_data.apply(lambda x: [item for sublist in x for item in sublist], axis=1)

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()

# Fit and transform the combined items to get one-hot encoded features
one_hot_encoded_data = mlb.fit_transform(combined_items)

# Create a DataFrame from the one-hot encoded data
df_one_hot = pd.DataFrame(one_hot_encoded_data, columns=mlb.classes_, index=df.index)

# Drop columns specified in columns_to_exclude
# Ensure that only columns actually present in df_one_hot are attempted to be dropped
cols_to_drop_from_one_hot = [col for col in columns_to_exclude if col in df_one_hot.columns]
if cols_to_drop_from_one_hot:
    df_one_hot = df_one_hot.drop(columns=cols_to_drop_from_one_hot)
    print(f"Dropped columns: {cols_to_drop_from_one_hot}")

# Drop the original 'rows_to_cols' from the main DataFrame
df_base = df.drop(columns=rows_to_cols)

# Concatenate the base DataFrame with the new one-hot encoded DataFrame
df_final = pd.concat([df_base, df_one_hot], axis=1)

print("Shape of the final DataFrame:", df_final.shape)
print("First 5 rows of the final DataFrame:")
display(df_final.head())

Dropped columns: ['ghjjjjjbv']
Shape of the final DataFrame: (26, 166)
First 5 rows of the final DataFrame:

/tmp/ipykernel_29071/1535957472.py:34: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  processed_data = df[rows_to_cols].applymap(clean_and_split)

,marca temporal,edad,genero,estrato,cuidad_origen,quien_vive,num_personas,quien_compra,mision_compra,lugar_compra,...,"shampoo, crema dental, jabon tocador, hilo dental, perfume, lociones","shampoo, crema dental, jabon tocador, proteccion femenina, crema de afeitar, hilo dental, perfume, lociones","shampoo, crema dental, jabon tocador, proteccion femenina, enjuague bucal, hilo dental, perfume, desodorantes","shampoo, crema dental, proteccion femenina, enjuague bucal, hilo dental, perfume, desodorantes, talcos",sixpack de leche,suavizantes,talcos,tomate,verduras,"verduras, pollo, cerdo, pescado, queso, jabon, crema dental, comida para el perro, arroz, papas fritas"
0,2026-04-01 16:40:21.529,22,Masculino,E3,mani casanare,Familia,3-4,Compartido,Semanal,Tienda de Barrio,...,0,0,0,0,0,1,0,0,0,0
1,2026-04-01 16:43:13.904,47,Femenino,E3,Bogotá,Familia,2,Yo,Mensual,"Hard Discount (D1, ARA, etc )",...,0,0,1,0,0,0,0,0,0,0
2,2026-04-01 16:44:10.287,24,Masculino,E4,Santa Marta,Padres,2,Compartido,Semanal,"Supermercado (Exito, Jumbo, Etc)",...,0,0,0,0,0,0,0,0,0,0
3,2026-04-01 16:52:20.537,20,Femenino,E4,Bogotá,Familia,2,Yo,Semanal,Tienda de Barrio,...,0,0,0,0,0,0,0,0,0,0
4,2026-04-01 19:31:11.449,20,Masculino,E2,Bogotá D.C.,Padres,3,Otra persona,Semanal,"Hard Discount (D1, ARA, etc )",...,0,0,0,0,0,0,0,0,0,0

In [8]:
from sklearn.preprocessing import MultiLabelBinarizer

# Function to clean and split the text data in the columns
def clean_and_split(text):
    if pd.isna(text) or not isinstance(text, str):
        return []

    # 1. Normalizar acentos
    text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')

    # 2. Lowercase
    text = text.lower()

    # 3. Reemplazar TODOS los separadores por coma
    text = re.sub(r'\n+', ',', text)           # saltos de línea
    text = re.sub(r'-\s*', ',', text)          # bullets tipo "- arroz"
    text = re.sub(r';', ',', text)             # por si acaso
    text = re.sub(r'\s{2,}', ',', text)        # espacios múltiples (casos raros)

    # 4. Limpiar comas duplicadas
    text = re.sub(r',+', ',', text)

    # 5. Split final
    items = [item.strip() for item in text.split(',') if item.strip()]

    # 6. Aplicar replace_map
    processed_items = [replace_map.get(item, item) for item in items]

    # 7. Eliminar duplicados
    return list(set(processed_items))

# Apply the cleaning and splitting to the relevant columns
processed_data = df[rows_to_cols].applymap(clean_and_split)

# Combine all lists of items for each row
# This creates a list of lists, where each inner list contains all items for a given row
combined_items = processed_data.apply(lambda x: [item for sublist in x for item in sublist], axis=1)

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()

# Fit and transform the combined items to get one-hot encoded features
one_hot_encoded_data = mlb.fit_transform(combined_items)

# Create a DataFrame from the one-hot encoded data
df_one_hot = pd.DataFrame(one_hot_encoded_data, columns=mlb.classes_, index=df.index)

# Drop the original 'rows_to_cols' from the main DataFrame
df_base = df.drop(columns=rows_to_cols)

# Concatenate the base DataFrame with the new one-hot encoded DataFrame
df_final = pd.concat([df_base, df_one_hot], axis=1)

print("Shape of the final DataFrame:", df_final.shape)
print("First 5 rows of the final DataFrame:")
display(df_final.head())

Shape of the final DataFrame: (26, 127)
First 5 rows of the final DataFrame:

/tmp/ipykernel_29071/1497301085.py:33: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  processed_data = df[rows_to_cols].applymap(clean_and_split)

,marca temporal,edad,genero,estrato,cuidad_origen,quien_vive,num_personas,quien_compra,mision_compra,lugar_compra,...,suavitel,suavizantes,talcos,te,tomate,un cafe,una paca de leche,uvas,verduras,vinos
0,2026-04-01 16:40:21.529,22,Masculino,E3,mani casanare,Familia,3-4,Compartido,Semanal,Tienda de Barrio,...,1,1,0,0,0,0,0,0,0,0
1,2026-04-01 16:43:13.904,47,Femenino,E3,Bogotá,Familia,2,Yo,Mensual,"Hard Discount (D1, ARA, etc )",...,0,1,0,0,0,0,0,0,0,0
2,2026-04-01 16:44:10.287,24,Masculino,E4,Santa Marta,Padres,2,Compartido,Semanal,"Supermercado (Exito, Jumbo, Etc)",...,0,1,1,0,0,0,0,0,0,0
3,2026-04-01 16:52:20.537,20,Femenino,E4,Bogotá,Familia,2,Yo,Semanal,Tienda de Barrio,...,0,1,0,0,0,0,0,0,0,0
4,2026-04-01 19:31:11.449,20,Masculino,E2,Bogotá D.C.,Padres,3,Otra persona,Semanal,"Hard Discount (D1, ARA, etc )",...,0,1,0,1,0,0,0,0,0,0

In [9]:
output_filename = 'df_final.xlsx'
df_final.to_excel(output_filename, index=False)
print(f"DataFrame saved to {output_filename}")

DataFrame saved to df_final.xlsx

In [10]:
from google.colab import files
files.download('df_final.xlsx')